# Use a base image
FROM nginx:latest
 
# Copy HTML and CSS files to the nginx web server directory
COPY index.html /usr/share/nginx/html
#COPY style.css /usr/share/nginx/html
 
# Expose port 80
EXPOSE 80